sudo: required
dist: trusty
services:
  - docker

language: go

go:
  - 1.8
  - 1.9

# Make sure project can also be built on travis for clones of the repo
go_import_path: github.com/marclop/elasticsearch-cli

install:
  - make vendor

script:
  - make test
